config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root "splash#index"
 devise_scope :user do  
     get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :users 
  
  resources :groups do
    resources :expenses
  end
  delete 'groups/:group_id/expenses/:id', to: 'expenses#destroy'
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: %i[show edit update destroy]
  before_action :set_group

  # GET /expenses or /expenses.json
  def index
    @expenses = @group.expenses.order(created_at: :desc)
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = @group.expenses.build
  end

  # GET /expenses/1/edit
  def edit
    @expense = @group.expenses.find(params[:id])
  end

  # POST /expenses or /expenses.json
  def create
    @expense = current_user.expenses.build(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to group_path(@group), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    @expense = @group.expenses.find(params[:id])

    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to group_path(@group), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense = @group.expenses.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to group_path(@group), notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = current_user.groups.find_by(id: params[:group_id])
  end

  def set_expense
    @expense = Expense.find_by(id: params[:expense_id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, :group_id)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_editexpense.html.erb
<%= form_with(model: [@group, @expense]) do |form| %> 
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="frm-input">
    <%= form.label :name,"Enter transaction name" , style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="frm-input">
    <%= form.label :amount,"Enter budget amount", style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div class="frm-input">
    <%= form.label "Choose the category" %>
     <%=form.collection_select :group_id, Group.order(:name), :id, :name  %>
  </div>

  <div class="frm-submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/_expenses.html.erb
<div class="expenses">
    <% @group.expenses.each do |expense| %>
      <div class="expense-item">
        <div class="expense-detail">
          <h2> <%= expense.name%></h2>
          <h3> $ <%= expense.amount%><h3>
        </div>

        <div class="expense-btn">
          <%= link_to "✎" "Edit this expense", edit_group_expense_path(@group,expense)%>
        </div>
      </div>
<% end %>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: [@group, @expense]) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="frm-input">
    <%= form.label :name,"Enter transaction name", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="frm-input">
    <%= form.label :amount,"Enter budget amount", style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div class="frm-input">
    <%= form.label "Choose the category" %>
     <%=form.collection_select :group_id, Group.order(:name), :id, :name  %>
  </div>

  <div class="frm-submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<div class="navbar">
  <h1 class="main-title"> Edit Transaction</h1>
  <% if user_signed_in? %>
     <%= link_to("Log out", destroy_user_session_path, method: :delete) %>    
  <% end %>
</div>

<div class="frm-categ">
   <%= render "editexpense", expense: @expense %>

   <br>

   <div class="back-trans">
      <%= link_to "Back to Transactions Page", group_expenses_path %>
   </div>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", expense %>
    </p>
  <% end %>
</div>

<%= link_to "New expense", new_group_expense_path %>

app/views/expenses/new.html.erb
<div class="navbar">
  <h1 class="main-title"> New Transactions</h1>
  <% if user_signed_in? %>
     <%= link_to("Log out", destroy_user_session_path, method: :delete) %>    
  <% end %>
</div>

<div class="frm-categ">
    <%= render "form", expense: @expense %>

    <br>

    <div class="to-group">
      <%= link_to "Back to Category Transactions", group_path(@group) %>
    </div>
</div>